# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school_and_educaation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
    ]
