# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person who gave the testimony.', max_length=50)),
                ('title', models.CharField(blank=True, help_text='Position of the person who gave the testimony.', max_length=50)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='accounts.UserProfile')),
            ],
        ),
    ]
