# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_skype_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stack_overflow_url',
            field=models.URLField(blank=True),
        ),
    ]
